[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.22"
tokio = { version = "1", features = ["full"], optional = true }

[features]
aio = ["redis/aio", "redis/tokio-comp", "tokio"]
